[workspace]
resolver = "3"
members = ["crates/cli", "crates/core", "crates/ui"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
serde = { version = "1.0.219", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.140", default-features = false, features = ["std"] }
thiserror = { version = "2.0.12", default-features = false }

[workspace.lints.rust]
unsafe_code = "forbid"
