[package]
name = "mire-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = ["events"] }
inkjet = { version = "0.11.1", default-features = false, features = ["language-bash", "language-css", "language-html", "language-javascript", "language-json", "language-python", "language-rust", "language-toml", "language-tsx", "language-typescript", "language-yaml"] }
mire-core = { path = "../core" }
serde.workspace = true
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm_0_29"] }
similar = { version = "2.7.0", default-features = false, features = ["inline"] }
terminal-colorsaurus = { version = "1.0.3", default-features = false }

[dev-dependencies]
divan = { version = "0.1.21", default-features = false, features = ["help"] }
insta = { version = "1.48.0", default-features = false }

[lints]
workspace = true

[[bench]]
name = "large_stream"
harness = false
